version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/dev/mongo/create-users-and-data.js:/docker-entrypoint-initdb.d/create-users-and-data.js"
    environment:
      MONGO_INITDB_DATABASE: "admin"
    expose:
      - "27017"

  postgresql:
    image: postgres:9.6-alpine
    container_name: postgresql
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/dev/postgresql/create_table_users.sql:/docker-entrypoint-initdb.d/create_table_users.sql"
    expose:
      - "5432"
    environment:
      POSTGRES_DB: "users"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "P@ssw0rd"

  x2crmdummy:
    image: mysql:5.6
    container_name: x2crmdummy
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/dev/x2crmdummy/create_x2contacts_table.sql:/docker-entrypoint-initdb.d/create_x2contacts_table.sql"
    expose:
      - "3306" 
    environment:
      MYSQL_ROOT_PASSWORD: "rootP@ssw0rd"
      MYSQL_DATABASE: "x2crm"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "P@ssw0rd"

  gamification:
    volumes:
      - "./config/dev/gamification/application.properties:/data/application.properties"
    ports:
      - 8081:8080
    depends_on:
      - mongo

  keepers:
    volumes:
      - "./config/dev/keepers/application.properties:/data/application.properties"
    ports:
      - 8082:8080
    depends_on:
      - mongo

  teams:
    volumes:
      - "./config/dev/teams/application.properties:/data/application.properties"
    ports:
      - 8083:8080
    depends_on:
      - mongo

  users:
    volumes:
      - "./config/dev/users/application.properties:/data/application.properties"
    ports:
      - 8084:8080
    depends_on:
      - postgresql
      - x2crmdummy

  keepers-slack-bot:
    volumes:
      - "./config/dev/keepers-slack-bot/application.properties:/data/application.properties"
    ports:
      - 8085:8080

  teams-slack-bot:
    volumes:
      - "./config/dev/teams-slack-bot/application.properties:/data/application.properties"
    ports:
      - 8086:8080

  gamification-slack-bot:
    volumes:
      - "./config/dev/gamification-slack-bot/application.properties:/data/application.properties"
    ports:
      - 8087:8080

  loadbalancer:
    ports:
      - "127.0.0.1:8080:80"