version: "3"
services:

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/dev/mongo/create-users.js:/docker-entrypoint-initdb.d/create-users.js"
    environment:
      MONGO_INITDB_DATABASE: "admin"
    expose:
      - "27017"

  postgresql:
    image: postgres:9.6-alpine
    container_name: postgresql
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/dev/postgresql/create_table_users.sql:/docker-entrypoint-initdb.d/create_table_users.sql"
    expose:
      - "5432"
    environment:
      POSTGRES_DB: "users"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "P@ssw0rd"
  
  x2crmdummy:
    image: mysql:5.6
    container_name: x2crmdummy
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/dev/x2crmdummy/create_x2contacts_table.sql:/docker-entrypoint-initdb.d/create_x2contacts_table.sql"
    expose:
      - "3306" 
    environment:
      MYSQL_ROOT_PASSWORD: "rootP@ssw0rd"
      MYSQL_DATABASE: "x2crm"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "P@ssw0rd"

  gamification:
    image: juja/gamification:latest
    container_name: gamification
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/dev/gamification/application.properties:/data/application.properties"
    links:
      - mongo
    ports:
      - 8081:8080
    depends_on:
      - mongo

  keepers:
    image: juja/keepers:latest
    container_name: keepers
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/dev/keepers/application.properties:/data/application.properties"
    links:
      - mongo
    ports:
      - 8082:8080
    depends_on:
      - mongo
  
  teams:
    image: juja/teams:latest
    container_name: teams
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/dev/teams/application.properties:/data/application.properties"
    links:
      - mongo
    ports:
      - 8083:8080
    depends_on:
      - mongo

  users:
    image: juja/users:latest
    container_name: users
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/dev/users/application.properties:/data/application.properties"
    links:
      - x2crmdummy
      - postgresql
    ports:
      - 8084:8080
    depends_on:
      - postgresql
      - x2crmdummy 
  
  keepers-slack-bot:
    image: juja/keepers-slack-bot:latest
    container_name: keepers-slack-bot
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/dev/keepers-slack-bot/application.properties:/data/application.properties"
    links:
      - keepers
      - users
    ports:
      - 8085:8080
    depends_on:
      - keepers
      - users

  teams-slack-bot:
    image: juja/teams-slack-bot:latest
    container_name: teams-slack-bot
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/dev/teams-slack-bot/application.properties:/data/application.properties"
    links:
      - teams
      - users
    ports:
      - 8086:8080
    depends_on:
      - teams
      - users

  gamification-slack-bot:
    image: juja/gamification-slack-bot:latest
    container_name: gamification-slack-bot
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/dev/gamification-slack-bot/application.properties:/data/application.properties"
    links:
      - gamification
      - teams
      - users
    ports:
      - 8087:8080
    depends_on:
      - teams
      - users
      - gamification